//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurchaseOrder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add product [{0}] to purchase order [{1}].
        /// </summary>
        internal static string AddItemToPurchaseOrderFailedErrorMessage {
            get {
                return ResourceManager.GetString("AddItemToPurchaseOrderFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProductToPurchaseOrder.
        /// </summary>
        internal static string AddProductToPurchaseOrderProc {
            get {
                return ResourceManager.GetString("AddProductToPurchaseOrderProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Product {0} to Supplier {1}.
        /// </summary>
        internal static string AddProductToSupplierLogMessage {
            get {
                return ResourceManager.GetString("AddProductToSupplierLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProductToSupplierBySupplierID.
        /// </summary>
        internal static string AddProductToSupplierProc {
            get {
                return ResourceManager.GetString("AddProductToSupplierProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=.;Database=HarroPODB;Trusted_Connection=True;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create purchase order for supplier: [{0}].
        /// </summary>
        internal static string CreatePurchaseOrderErrorMessage {
            get {
                return ResourceManager.GetString("CreatePurchaseOrderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePurchaseOrder.
        /// </summary>
        internal static string CreatePurchaseOrderProc {
            get {
                return ResourceManager.GetString("CreatePurchaseOrderProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Supplier.
        /// </summary>
        internal static string CreateSupplierError {
            get {
                return ResourceManager.GetString("CreateSupplierError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSupplier.
        /// </summary>
        internal static string CreateSupplierProc {
            get {
                return ResourceManager.GetString("CreateSupplierProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Supplier In Database with Supplier Code {0}.
        /// </summary>
        internal static string CreatingSupplierLogMessage {
            get {
                return ResourceManager.GetString("CreatingSupplierLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductByProductId.
        /// </summary>
        internal static string DeleteProductByIdProc {
            get {
                return ResourceManager.GetString("DeleteProductByIdProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductFromPurchaseOrderById.
        /// </summary>
        internal static string DeleteProductFromPOByIdProc {
            get {
                return ResourceManager.GetString("DeleteProductFromPOByIdProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting product: {0} by product ID.
        /// </summary>
        internal static string DeletingProductbyId {
            get {
                return ResourceManager.GetString("DeletingProductbyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchAll.
        /// </summary>
        internal static string FetchAllParameterName {
            get {
                return ResourceManager.GetString("FetchAllParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductByID.
        /// </summary>
        internal static string GetProductByIdProc {
            get {
                return ResourceManager.GetString("GetProductByIdProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductByProductCode.
        /// </summary>
        internal static string GetProductByProductCodeProc {
            get {
                return ResourceManager.GetString("GetProductByProductCodeProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Product {0} from database.
        /// </summary>
        internal static string GetProductByProductIdLogMessage {
            get {
                return ResourceManager.GetString("GetProductByProductIdLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPurchaseOrderItemsByID.
        /// </summary>
        internal static string GetPurchaseOrderItemsProc {
            get {
                return ResourceManager.GetString("GetPurchaseOrderItemsProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPurchaseOrderByID.
        /// </summary>
        internal static string GetPurchaseOrderProc {
            get {
                return ResourceManager.GetString("GetPurchaseOrderProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPurchaseOrdersBySupplierID.
        /// </summary>
        internal static string GetPurchaseOrdersBySupplierProc {
            get {
                return ResourceManager.GetString("GetPurchaseOrdersBySupplierProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSupplierBySupplierCode.
        /// </summary>
        internal static string GetSupplierByCodeProc {
            get {
                return ResourceManager.GetString("GetSupplierByCodeProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSupplierByID.
        /// </summary>
        internal static string GetSupplierByIdProc {
            get {
                return ResourceManager.GetString("GetSupplierByIdProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdParameter {
            get {
                return ResourceManager.GetString("IdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeDeleted.
        /// </summary>
        internal static string IsDeletedParameterName {
            get {
                return ResourceManager.GetString("IsDeletedParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameParameterName {
            get {
                return ResourceManager.GetString("NameParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No purchase orders found for supplier {0} in the database..
        /// </summary>
        internal static string NoPurchaseOrdersForSupplierErrorMessage {
            get {
                return ResourceManager.GetString("NoPurchaseOrdersForSupplierErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseOrderID.
        /// </summary>
        internal static string POIdParameterName {
            get {
                return ResourceManager.GetString("POIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        internal static string ProductCodeParameterName {
            get {
                return ResourceManager.GetString("ProductCodeParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ProductDescriptionParameterName {
            get {
                return ResourceManager.GetString("ProductDescriptionParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} does not exist..
        /// </summary>
        internal static string ProductDoesNotExistsErrorMessage {
            get {
                return ResourceManager.GetString("ProductDoesNotExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create product, the product code is in use..
        /// </summary>
        internal static string ProductExistsErrorMessage {
            get {
                return ResourceManager.GetString("ProductExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID.
        /// </summary>
        internal static string ProductIdParameterName {
            get {
                return ResourceManager.GetString("ProductIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} not found.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ProductPriceParameterName {
            get {
                return ResourceManager.GetString("ProductPriceParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchDescription.
        /// </summary>
        internal static string ProductSeachParameterName {
            get {
                return ResourceManager.GetString("ProductSeachParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseOrderID.
        /// </summary>
        internal static string PurchaseOrderIdParamName {
            get {
                return ResourceManager.GetString("PurchaseOrderIdParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PurchaseOrderQuantityParameterName {
            get {
                return ResourceManager.GetString("PurchaseOrderQuantityParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for products with search string {0}.
        /// </summary>
        internal static string SearchProductsLogMessage {
            get {
                return ResourceManager.GetString("SearchProductsLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchProductsByDescription.
        /// </summary>
        internal static string SearchProductsProc {
            get {
                return ResourceManager.GetString("SearchProductsProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create supplier Supplier {0} already exists.
        /// </summary>
        internal static string SupplierAlreadyExistsError {
            get {
                return ResourceManager.GetString("SupplierAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierCode.
        /// </summary>
        internal static string SupplierCodeParameterName {
            get {
                return ResourceManager.GetString("SupplierCodeParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplier does not exist in the database.
        /// </summary>
        internal static string SupplierDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("SupplierDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierID.
        /// </summary>
        internal static string SupplierIdParameterName {
            get {
                return ResourceManager.GetString("SupplierIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string SupplierSearchParameterName {
            get {
                return ResourceManager.GetString("SupplierSearchParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchSupplierByName.
        /// </summary>
        internal static string SupplierSearchProcName {
            get {
                return ResourceManager.GetString("SupplierSearchProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateProductByProductID.
        /// </summary>
        internal static string UpdateProductProc {
            get {
                return ResourceManager.GetString("UpdateProductProc", resourceCulture);
            }
        }
    }
}
