//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurchaseOrder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Supplier.
        /// </summary>
        internal static string CreateSupplierError {
            get {
                return ResourceManager.GetString("CreateSupplierError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSupplier.
        /// </summary>
        internal static string CreateSupplierProc {
            get {
                return ResourceManager.GetString("CreateSupplierProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSupplierByID.
        /// </summary>
        internal static string GetSupplierByIdProc {
            get {
                return ResourceManager.GetString("GetSupplierByIdProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdParameter {
            get {
                return ResourceManager.GetString("IdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameParameterName {
            get {
                return ResourceManager.GetString("NameParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseOrderID.
        /// </summary>
        internal static string POIdParameterName {
            get {
                return ResourceManager.GetString("POIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        internal static string ProductCodeParameterName {
            get {
                return ResourceManager.GetString("ProductCodeParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierSearchParameterName.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create supplier Supplier already exists.
        /// </summary>
        internal static string SupplierAlreadyExistsError {
            get {
                return ResourceManager.GetString("SupplierAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierCode.
        /// </summary>
        internal static string SupplierCodeParameterName {
            get {
                return ResourceManager.GetString("SupplierCodeParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string SupplierSearchParameterName {
            get {
                return ResourceManager.GetString("SupplierSearchParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchSupplierByName.
        /// </summary>
        internal static string SupplierSearchProcName {
            get {
                return ResourceManager.GetString("SupplierSearchProcName", resourceCulture);
            }
        }
    }
}
