CREATE DATABASE [HarroPODB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HarroPODB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HarroPODB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HarroPODB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HarroPODB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HarroPODB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HarroPODB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HarroPODB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HarroPODB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HarroPODB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HarroPODB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HarroPODB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HarroPODB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HarroPODB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HarroPODB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HarroPODB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HarroPODB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HarroPODB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HarroPODB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HarroPODB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HarroPODB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HarroPODB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HarroPODB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HarroPODB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HarroPODB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HarroPODB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HarroPODB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HarroPODB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HarroPODB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HarroPODB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HarroPODB] SET  MULTI_USER 
GO

ALTER DATABASE [HarroPODB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HarroPODB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HarroPODB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HarroPODB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HarroPODB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HarroPODB] SET  READ_WRITE 
GO


